import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'

import { useState } from 'react'
import dynamic from 'next/dynamic'

const Menu = dynamic(() => import('../components/menu'), {
  ssr: false,
})

const ethers = require('ethers')


async function generateKeyPair (){
    const newWallet = await ethers.Wallet.createRandom();
    console.log(newWallet);
}

const TokenRequest: NextPage = () => {
  const [publicKey, setPublicKey] = useState("");
  const [privateKey, setPrivateKey] = useState("");
  async function generateKeyPair (){
    const newWallet = await ethers.Wallet.createRandom();
    
    setPublicKey(newWallet.publicKey);
    setPrivateKey(newWallet.privateKey);
}

  return (
    <div className={styles.container}>
      <Script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"/>
      <Head>
        <title>Week 4 - Ballot</title>
        <meta name="description" content="Generated by create next app - a project made by ProtocolWhisper and JoVi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu></Menu>
        <div className='d-inline-block justify-text-left mb-5 pb-5'>
        <h4><a href='/' className='text-black'> Home</a></h4>
        </div>
        <div className="justify-text-center">
          <div className="grid">
              
                <div className="input-group-lg mb-3 ">
                  
                  <h3 className='text-white'>Public Key</h3>
                  <input type="text" className="form-control" value={publicKey} placeholder='Public Key' id='1' disabled />
                  
                  <br/>
                </div>
                
                <div className="input-group-lg mb-3">
                <h3 className='text-white'>Private Key</h3>
                  <input type="text" className="form-control" value={privateKey} placeholder='Private Key' disabled/>
                  
                </div>
              
              
              <button className='btn btn-light btn-lg btn-outline-danger justify-text-center container' onClick={generateKeyPair}>Generate a new key-pair</button>
              
          </div>  
        </div>
      </main>

      <Footer></Footer>
    </div>
  )
}

export default TokenRequest
